adminUser:
  password: local:mentordigital/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: devops@mentordigital.no
  token: local:mentordigital/pipelineUser:token
  username: mentor-jenkins
prow:
  hmacToken: local:mentordigital/prow:hmacToken
filebeat:
  cloudId: local:mentordigital/filebeat:cloudId
  cloudAuth: local:mentordigital/filebeat:cloudAuth